// Generated by Microsoft TypeSpec

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: resources/v1/resource_data.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterStatus int32

const (
	ClusterStatus_CLUSTER_STATUS_UNSPECIFIED ClusterStatus = 0
	ClusterStatus_CLUSTER_STATUS_OTHER       ClusterStatus = 1
	ClusterStatus_READY                      ClusterStatus = 2
	ClusterStatus_FAILED                     ClusterStatus = 3
	ClusterStatus_OFFLINE                    ClusterStatus = 4
)

// Enum value maps for ClusterStatus.
var (
	ClusterStatus_name = map[int32]string{
		0: "CLUSTER_STATUS_UNSPECIFIED",
		1: "CLUSTER_STATUS_OTHER",
		2: "READY",
		3: "FAILED",
		4: "OFFLINE",
	}
	ClusterStatus_value = map[string]int32{
		"CLUSTER_STATUS_UNSPECIFIED": 0,
		"CLUSTER_STATUS_OTHER":       1,
		"READY":                      2,
		"FAILED":                     3,
		"OFFLINE":                    4,
	}
)

func (x ClusterStatus) Enum() *ClusterStatus {
	p := new(ClusterStatus)
	*p = x
	return p
}

func (x ClusterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_v1_resource_data_proto_enumTypes[0].Descriptor()
}

func (ClusterStatus) Type() protoreflect.EnumType {
	return &file_resources_v1_resource_data_proto_enumTypes[0]
}

func (x ClusterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterStatus.Descriptor instead.
func (ClusterStatus) EnumDescriptor() ([]byte, []int) {
	return file_resources_v1_resource_data_proto_rawDescGZIP(), []int{0}
}

type KubeVendor int32

const (
	KubeVendor_KUBE_VENDOR_UNSPECIFIED KubeVendor = 0
	KubeVendor_KUBE_VENDOR_OTHER       KubeVendor = 1
	KubeVendor_AKS                     KubeVendor = 2
	KubeVendor_EKS                     KubeVendor = 3
	KubeVendor_IKS                     KubeVendor = 4
	KubeVendor_OPENSHIFT               KubeVendor = 5
	KubeVendor_GKE                     KubeVendor = 6
)

// Enum value maps for KubeVendor.
var (
	KubeVendor_name = map[int32]string{
		0: "KUBE_VENDOR_UNSPECIFIED",
		1: "KUBE_VENDOR_OTHER",
		2: "AKS",
		3: "EKS",
		4: "IKS",
		5: "OPENSHIFT",
		6: "GKE",
	}
	KubeVendor_value = map[string]int32{
		"KUBE_VENDOR_UNSPECIFIED": 0,
		"KUBE_VENDOR_OTHER":       1,
		"AKS":                     2,
		"EKS":                     3,
		"IKS":                     4,
		"OPENSHIFT":               5,
		"GKE":                     6,
	}
)

func (x KubeVendor) Enum() *KubeVendor {
	p := new(KubeVendor)
	*p = x
	return p
}

func (x KubeVendor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KubeVendor) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_v1_resource_data_proto_enumTypes[1].Descriptor()
}

func (KubeVendor) Type() protoreflect.EnumType {
	return &file_resources_v1_resource_data_proto_enumTypes[1]
}

func (x KubeVendor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KubeVendor.Descriptor instead.
func (KubeVendor) EnumDescriptor() ([]byte, []int) {
	return file_resources_v1_resource_data_proto_rawDescGZIP(), []int{1}
}

type HostStatus int32

const (
	HostStatus_ENABLED  HostStatus = 0
	HostStatus_DISABLED HostStatus = 1
)

// Enum value maps for HostStatus.
var (
	HostStatus_name = map[int32]string{
		0: "ENABLED",
		1: "DISABLED",
	}
	HostStatus_value = map[string]int32{
		"ENABLED":  0,
		"DISABLED": 1,
	}
)

func (x HostStatus) Enum() *HostStatus {
	p := new(HostStatus)
	*p = x
	return p
}

func (x HostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_v1_resource_data_proto_enumTypes[2].Descriptor()
}

func (HostStatus) Type() protoreflect.EnumType {
	return &file_resources_v1_resource_data_proto_enumTypes[2]
}

func (x HostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostStatus.Descriptor instead.
func (HostStatus) EnumDescriptor() ([]byte, []int) {
	return file_resources_v1_resource_data_proto_rawDescGZIP(), []int{2}
}

type K8SClusterResourceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExternalClusterId string        `protobuf:"bytes,219571597,opt,name=external_cluster_id,json=externalClusterId,proto3" json:"external_cluster_id,omitempty"`
	KubeVersion       string        `protobuf:"bytes,395858490,opt,name=kube_version,json=kubeVersion,proto3" json:"kube_version,omitempty"`
	ClusterStatus     ClusterStatus `protobuf:"varint,395858492,opt,name=cluster_status,json=clusterStatus,proto3,enum=resources.v1.ClusterStatus" json:"cluster_status,omitempty"`
	KubeVendor        KubeVendor    `protobuf:"varint,395858494,opt,name=kube_vendor,json=kubeVendor,proto3,enum=resources.v1.KubeVendor" json:"kube_vendor,omitempty"`
}

func (x *K8SClusterResourceData) Reset() {
	*x = K8SClusterResourceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_v1_resource_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *K8SClusterResourceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*K8SClusterResourceData) ProtoMessage() {}

func (x *K8SClusterResourceData) ProtoReflect() protoreflect.Message {
	mi := &file_resources_v1_resource_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use K8SClusterResourceData.ProtoReflect.Descriptor instead.
func (*K8SClusterResourceData) Descriptor() ([]byte, []int) {
	return file_resources_v1_resource_data_proto_rawDescGZIP(), []int{0}
}

func (x *K8SClusterResourceData) GetExternalClusterId() string {
	if x != nil {
		return x.ExternalClusterId
	}
	return ""
}

func (x *K8SClusterResourceData) GetKubeVersion() string {
	if x != nil {
		return x.KubeVersion
	}
	return ""
}

func (x *K8SClusterResourceData) GetClusterStatus() ClusterStatus {
	if x != nil {
		return x.ClusterStatus
	}
	return ClusterStatus_CLUSTER_STATUS_UNSPECIFIED
}

func (x *K8SClusterResourceData) GetKubeVendor() KubeVendor {
	if x != nil {
		return x.KubeVendor
	}
	return KubeVendor_KUBE_VENDOR_UNSPECIFIED
}

type RhelHostResourceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId     string     `protobuf:"bytes,219571597,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	OsVersion  string     `protobuf:"bytes,395858490,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	HostStatus HostStatus `protobuf:"varint,395858491,opt,name=host_status,json=hostStatus,proto3,enum=resources.v1.HostStatus" json:"host_status,omitempty"`
}

func (x *RhelHostResourceData) Reset() {
	*x = RhelHostResourceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_v1_resource_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RhelHostResourceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RhelHostResourceData) ProtoMessage() {}

func (x *RhelHostResourceData) ProtoReflect() protoreflect.Message {
	mi := &file_resources_v1_resource_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RhelHostResourceData.ProtoReflect.Descriptor instead.
func (*RhelHostResourceData) Descriptor() ([]byte, []int) {
	return file_resources_v1_resource_data_proto_rawDescGZIP(), []int{1}
}

func (x *RhelHostResourceData) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RhelHostResourceData) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RhelHostResourceData) GetHostStatus() HostStatus {
	if x != nil {
		return x.HostStatus
	}
	return HostStatus_ENABLED
}

var File_resources_v1_resource_data_proto protoreflect.FileDescriptor

var file_resources_v1_resource_data_proto_rawDesc = []byte{
	0x0a, 0x20, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x22, 0xf9, 0x01, 0x0a, 0x16, 0x4b, 0x38, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x13, 0x65,
	0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x8d, 0xcb, 0xd9, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x65, 0x78, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0c, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0xba,
	0xa4, 0xe1, 0xbc, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6b, 0x75, 0x62, 0x65, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x46, 0x0a, 0x0e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0xbc, 0xa4, 0xe1, 0xbc, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3d, 0x0a,
	0x0b, 0x6b, 0x75, 0x62, 0x65, 0x5f, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x18, 0xbe, 0xa4, 0xe1,
	0xbc, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x52, 0x0a, 0x6b, 0x75, 0x62, 0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x22, 0x94, 0x01, 0x0a,
	0x14, 0x52, 0x68, 0x65, 0x6c, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x8d, 0xcb, 0xd9, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x21, 0x0a, 0x0a, 0x6f, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0xba, 0xa4, 0xe1, 0xbc, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x73, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x0b, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0xbb, 0xa4, 0xe1, 0xbc, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x68, 0x6f, 0x73, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2a, 0x6d, 0x0a, 0x0d, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45,
	0x10, 0x04, 0x2a, 0x73, 0x0a, 0x0a, 0x4b, 0x75, 0x62, 0x65, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72,
	0x12, 0x1b, 0x0a, 0x17, 0x4b, 0x55, 0x42, 0x45, 0x5f, 0x56, 0x45, 0x4e, 0x44, 0x4f, 0x52, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x11, 0x4b, 0x55, 0x42, 0x45, 0x5f, 0x56, 0x45, 0x4e, 0x44, 0x4f, 0x52, 0x5f, 0x4f, 0x54, 0x48,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4b, 0x53, 0x10, 0x02, 0x12, 0x07, 0x0a,
	0x03, 0x45, 0x4b, 0x53, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4b, 0x53, 0x10, 0x04, 0x12,
	0x0d, 0x0a, 0x09, 0x4f, 0x50, 0x45, 0x4e, 0x53, 0x48, 0x49, 0x46, 0x54, 0x10, 0x05, 0x12, 0x07,
	0x0a, 0x03, 0x47, 0x4b, 0x45, 0x10, 0x06, 0x2a, 0x27, 0x0a, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01,
	0x42, 0x4d, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x6f, 0x6e, 0x79, 0x74, 0x68, 0x65, 0x6c, 0x65, 0x67, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resources_v1_resource_data_proto_rawDescOnce sync.Once
	file_resources_v1_resource_data_proto_rawDescData = file_resources_v1_resource_data_proto_rawDesc
)

func file_resources_v1_resource_data_proto_rawDescGZIP() []byte {
	file_resources_v1_resource_data_proto_rawDescOnce.Do(func() {
		file_resources_v1_resource_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_resources_v1_resource_data_proto_rawDescData)
	})
	return file_resources_v1_resource_data_proto_rawDescData
}

var file_resources_v1_resource_data_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_resources_v1_resource_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resources_v1_resource_data_proto_goTypes = []any{
	(ClusterStatus)(0),             // 0: resources.v1.ClusterStatus
	(KubeVendor)(0),                // 1: resources.v1.KubeVendor
	(HostStatus)(0),                // 2: resources.v1.HostStatus
	(*K8SClusterResourceData)(nil), // 3: resources.v1.K8sClusterResourceData
	(*RhelHostResourceData)(nil),   // 4: resources.v1.RhelHostResourceData
}
var file_resources_v1_resource_data_proto_depIdxs = []int32{
	0, // 0: resources.v1.K8sClusterResourceData.cluster_status:type_name -> resources.v1.ClusterStatus
	1, // 1: resources.v1.K8sClusterResourceData.kube_vendor:type_name -> resources.v1.KubeVendor
	2, // 2: resources.v1.RhelHostResourceData.host_status:type_name -> resources.v1.HostStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resources_v1_resource_data_proto_init() }
func file_resources_v1_resource_data_proto_init() {
	if File_resources_v1_resource_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resources_v1_resource_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*K8SClusterResourceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_v1_resource_data_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RhelHostResourceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resources_v1_resource_data_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resources_v1_resource_data_proto_goTypes,
		DependencyIndexes: file_resources_v1_resource_data_proto_depIdxs,
		EnumInfos:         file_resources_v1_resource_data_proto_enumTypes,
		MessageInfos:      file_resources_v1_resource_data_proto_msgTypes,
	}.Build()
	File_resources_v1_resource_data_proto = out.File
	file_resources_v1_resource_data_proto_rawDesc = nil
	file_resources_v1_resource_data_proto_goTypes = nil
	file_resources_v1_resource_data_proto_depIdxs = nil
}
